log_level: INFO
storage:
  node_type: "Normal"
  hnsw_index:
    m: 16
    ef_construct: 120
    full_scan_threshold_kb: 10000
  collection:
    quantization: null
service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
cluster:
  enabled: false
telemetry_disabled: true
